services:
  flower-kb:
    build: .
    ports:
      - "3088:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    dns:
      - 223.5.5.5
      - 114.114.114.114
